# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.srcs/sources_1/bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.gen/sources_1/bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.gen/sources_1/bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.srcs/sources_1/bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'bd_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.gen/sources_1/bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.gen/sources_1/bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
