# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bd/bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_zynq_ultra_ps_e_0_0/bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: /home/caccolillo/Documents/ultra96_vivado_projects/Ultra96_v2_repo/ps_prj/ultra96_basic_system/ultra96_basic_system.gen/sources_1/bd/bd/bd_ooc.xdc
